name: Set Environment Variables

on:
  push:
    branches:
      - picturae_import
      - master

jobs:
  set-env:
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variables
        env:
          BOT_USER: ${{ secrets.BOT_USER }}
          BOT_PASS: ${{ secrets.BOT_PASS}}
        run: |
          echo "New environment variables set."